name: Obfuscate JavaScript

on:
  push:
    branches: [ master ]
    paths:
      - 'static/autoxpress.js'

permissions:
  contents: write

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install javascript-obfuscator
        
      - name: Verify file exists
        run: |
          ls -la
          ls -la static/
          echo "Checking if file exists..."
          if [ -f "static/autoxpress.js" ]; then
            echo "✅ File exists!"
          else
            echo "❌ File not found!"
            exit 1
          fi
        
      - name: Obfuscate JavaScript
        run: |
          node -e "
          const fs = require('fs');
          const JavaScriptObfuscator = require('javascript-obfuscator');
          
          // Path to your JavaScript file
          const jsPath = './static/autoxpress.js';
          
          console.log('Reading file:', jsPath);
          // Read the JavaScript file
          const jsContent = fs.readFileSync(jsPath, 'utf8');
          console.log('File content length:', jsContent.length);
          
          // Copyright notice to prepend
          const copyright = '/*\\n * Copyright (c) 2025 AutoXpress. All rights reserved.\\n * Unauthorized reproduction or distribution of this code is strictly prohibited.\\n * This software is proprietary and confidential.\\n */\\n\\n';
          
          // Only obfuscate if content doesn't already contain obfuscated markers
          if (!jsContent.includes('_0x')) {
            console.log('Obfuscating JavaScript...');
            // Obfuscate the code with effective settings
            const obfuscatedCode = JavaScriptObfuscator.obfuscate(jsContent, {
              compact: true,
              controlFlowFlattening: true,
              controlFlowFlatteningThreshold: 0.5,
              deadCodeInjection: true,
              deadCodeInjectionThreshold: 0.3,
              debugProtection: false,
              disableConsoleOutput: false,
              identifierNamesGenerator: 'hexadecimal',
              log: false,
              renameGlobals: false,
              rotateStringArray: true,
              selfDefending: true,
              stringArray: true,
              stringArrayEncoding: ['base64'],
              stringArrayThreshold: 0.8,
              transformObjectKeys: true,
              unicodeEscapeSequence: false
            }).getObfuscatedCode();
            
            // Write the obfuscated code back to the file with copyright
            fs.writeFileSync(jsPath, copyright + obfuscatedCode);
            console.log('JavaScript obfuscation complete!');
          } else {
            console.log('File appears to be already obfuscated, skipping...');
          }
          "
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code static/autoxpress.js || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit obfuscated files
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add static/autoxpress.js
          git commit -m "Obfuscate JavaScript [automated]"
          git push